package com.ecommers.model;// default package
// Generated 24-Jun-2025, 10:41:08 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_id") 
)
public class Customer  implements java.io.Serializable {

     private int customerId;
     private Users users;
     private String firstname;
     private String lastname;
     private Set orderses = new HashSet(0);
     private Set deliveryAddresses = new HashSet(0);

    public Customer() {
    }

	
    public Customer(int customerId, Users users) {
        this.customerId = customerId;
        this.users = users;
    }
    public Customer(int customerId, Users users, String firstname, String lastname, Set orderses, Set deliveryAddresses) {
       this.customerId = customerId;
       this.users = users;
       this.firstname = firstname;
       this.lastname = lastname;
       this.orderses = orderses;
       this.deliveryAddresses = deliveryAddresses;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="customer_id", unique=true, nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    @OneToOne (fetch=FetchType.LAZY,cascade = CascadeType.ALL)
    @JoinColumn(name="user_id", unique=true, nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="firstname", length=200)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", length=200)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<DeliveryAddress> getDeliveryAddresses() {
        return this.deliveryAddresses;
    }
    
    public void setDeliveryAddresses(Set<DeliveryAddress>deliveryAddresses) {
        this.deliveryAddresses = deliveryAddresses;
    }




}


