package com.ecommers.model;// default package
// Generated 24-Jun-2025, 10:41:08 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryAddress generated by hbm2java
 */
@Entity
@Table(name="delivery_address"
)
public class DeliveryAddress  implements java.io.Serializable {


     private int deliveryAddressId;
     private Customer customer;
     private String addressLine;
     private String city;
     private String state;
     private int pincode;
     private String country;
     private String type;
     private Set orderses = new HashSet(0);

    public DeliveryAddress() {
    }

	
    public DeliveryAddress(int deliveryAddressId, String addressLine, String city, String state, int pincode) {
        this.deliveryAddressId = deliveryAddressId;
        this.addressLine = addressLine;
        this.city = city;
        this.state = state;
        this.pincode = pincode;
    }
    public DeliveryAddress(int deliveryAddressId, Customer customer, String addressLine, String city, String state, int pincode, String country, String type, Set orderses) {
       this.deliveryAddressId = deliveryAddressId;
       this.customer = customer;
       this.addressLine = addressLine;
       this.city = city;
       this.state = state;
       this.pincode = pincode;
       this.country = country;
       this.type = type;
       this.orderses = orderses;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="delivery_address_id", unique=true, nullable=false)
    public int getDeliveryAddressId() {
        return this.deliveryAddressId;
    }
    
    public void setDeliveryAddressId(int deliveryAddressId) {
        this.deliveryAddressId = deliveryAddressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="address_line", nullable=false)
    public String getAddressLine() {
        return this.addressLine;
    }
    
    public void setAddressLine(String addressLine) {
        this.addressLine = addressLine;
    }

    
    @Column(name="city", nullable=false, length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", nullable=false, length=100)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="pincode", nullable=false, precision=6, scale=0)
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="country", length=100)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="type", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="deliveryAddress")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


