package com.ecommers.model;
// Generated 31-May-2025, 5:05:44 pm by Hibernate Tools 4.0.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.time.LocalDateTime;


/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name="discount"
    ,schema="public"
)
public class Discount implements java.io.Serializable {


     private int discountId;
     private Product product;
     private Integer discountPercent;
     private LocalDateTime startLocalDateTime;
     private LocalDateTime endLocalDateTime;
     private LocalDateTime createdDate;
     private LocalDateTime updatedDate;

    public Discount() {
    }

	
    public Discount(int discountId) {
        this.discountId = discountId;
    }
    public Discount(int discountId, Product product, Integer discountPercent, LocalDateTime startLocalDateTime, LocalDateTime endLocalDateTime, LocalDateTime createdDate, LocalDateTime updatedDate) {
       this.discountId = discountId;
       this.product = product;
       this.discountPercent = discountPercent;
       this.startLocalDateTime = startLocalDateTime;
       this.endLocalDateTime = endLocalDateTime;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="discount_id", unique=true, nullable=false)
    public int getDiscountId() {
        return this.discountId;
    }
    
    public void setDiscountId(int discountId) {
        this.discountId = discountId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="discount_percent", precision=5, scale=0)
    public Integer getDiscountPercent() {
        return this.discountPercent;
    }
    
    public void setDiscountPercent(Integer discountPercent) {
        this.discountPercent = discountPercent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_LocalDateTime", length=29)
    public LocalDateTime getStartLocalDateTime() {
        return this.startLocalDateTime;
    }
    
    public void setStartLocalDateTime(LocalDateTime startLocalDateTime) {
        this.startLocalDateTime = startLocalDateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_LocalDateTime", length=29)
    public LocalDateTime getEndLocalDateTime() {
        return this.endLocalDateTime;
    }
    
    public void setEndLocalDateTime(LocalDateTime endLocalDateTime) {
        this.endLocalDateTime = endLocalDateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_LocalDateTime", length=29)
    public LocalDateTime getcreatedDate() {
        return this.createdDate;
    }
    
    public void setcreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="upLocalDateTimed_LocalDateTime", length=29)
    public LocalDateTime getupdatedDate() {
        return this.updatedDate;
    }
    
    public void setupdatedDate(LocalDateTime updatedDate) {
        this.updatedDate = updatedDate;
    }


}


