package com.ecommers.model;
// Generated 31-May-2025, 5:05:44 pm by Hibernate Tools 4.0.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.time.LocalDateTime;


/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name="inventory"
    ,schema="public"
)
public class Inventory implements java.io.Serializable {


     private int inventoryId;
     private Product product;
     private int stockQuantity;
     private LocalDateTime upLocalDateTimedAt;

    public Inventory() {
    }

	
    public Inventory(int inventoryId, int stockQuantity, LocalDateTime upLocalDateTimedAt) {
        this.inventoryId = inventoryId;
        this.stockQuantity = stockQuantity;
        this.upLocalDateTimedAt = upLocalDateTimedAt;
    }
    public Inventory(int inventoryId, Product product, int stockQuantity, LocalDateTime upLocalDateTimedAt) {
       this.inventoryId = inventoryId;
       this.product = product;
       this.stockQuantity = stockQuantity;
       this.upLocalDateTimedAt = upLocalDateTimedAt;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="inventory_id", unique=true, nullable=false)
    public int getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(int inventoryId) {
        this.inventoryId = inventoryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="stock_quantity", nullable=false)
    public int getStockQuantity() {
        return this.stockQuantity;
    }
    
    public void setStockQuantity(int stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="upLocalDateTimed_at", nullable=false, length=29)
    public LocalDateTime getUpLocalDateTimedAt() {
        return this.upLocalDateTimedAt;
    }
    
    public void setUpLocalDateTimedAt(LocalDateTime upLocalDateTimedAt) {
        this.upLocalDateTimedAt = upLocalDateTimedAt;
    }




}


