package com.ecommers.model;// default package
// Generated 24-Jun-2025, 10:41:08 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.math.BigDecimal;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name="order_items"
)
public class OrderItems  implements java.io.Serializable {


     private int orderItemId;
     private Product product;
     private Orders orders;
     private Integer quantity;
     private BigDecimal price;
     private BigDecimal totalAmount;

    public OrderItems() {
    }

	
    public OrderItems(int orderItemId, Product product, Orders orders, BigDecimal price, BigDecimal totalAmount) {
        this.orderItemId = orderItemId;
        this.product = product;
        this.orders = orders;
        this.price = price;
        this.totalAmount = totalAmount;
    }
    public OrderItems(int orderItemId, Product product, Orders orders, Integer quantity, BigDecimal price, BigDecimal totalAmount) {
       this.orderItemId = orderItemId;
       this.product = product;
       this.orders = orders;
       this.quantity = quantity;
       this.price = price;
       this.totalAmount = totalAmount;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="order_item_id", unique=true, nullable=false)
    public int getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(int orderItemId) {
        this.orderItemId = orderItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=10, scale=2)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="total_amount", nullable=false, precision=10, scale=2)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }




}


