package com.ecommers.model;// default package
// Generated 24-Jun-2025, 10:41:08 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
)
public class Orders  implements java.io.Serializable {


     private int orderId;
     private DeliveryAddress deliveryAddress;
     private Customer customer;
     private Date orderDate;
     private Date orderUpdateDate;
     private BigDecimal totalAmount;
     private Set orderItemses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(int orderId, Date orderDate, BigDecimal totalAmount) {
        this.orderId = orderId;
        this.orderDate = orderDate;
        this.totalAmount = totalAmount;
    }
    public Orders(int orderId, DeliveryAddress deliveryAddress, Customer customer, Date orderDate, Date orderUpdateDate, BigDecimal totalAmount, Set orderItemses) {
       this.orderId = orderId;
       this.deliveryAddress = deliveryAddress;
       this.customer = customer;
       this.orderDate = orderDate;
       this.orderUpdateDate = orderUpdateDate;
       this.totalAmount = totalAmount;
       this.orderItemses = orderItemses;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="order_id", unique=true, nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="delivery_address_id")
    public DeliveryAddress getDeliveryAddress() {
        return this.deliveryAddress;
    }
    
    public void setDeliveryAddress(DeliveryAddress deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="order_date", nullable=false, length=13)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="order_update_date", length=13)
    public Date getOrderUpdateDate() {
        return this.orderUpdateDate;
    }
    
    public void setOrderUpdateDate(Date orderUpdateDate) {
        this.orderUpdateDate = orderUpdateDate;
    }

    @Column(name="total_amount", nullable=false, precision=10, scale=2)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrderItems> getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set<OrderItems> orderItemses) {
        this.orderItemses = orderItemses;
    }




}


