package com.ecommers.model;
// Generated 31-May-2025, 5:05:44 pm by Hibernate Tools 4.0.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.time.LocalDate;

/**
 * ProductImage generated by hbm2java
 */
@Entity
@Table(name="product_image"
)
public class ProductImage  implements java.io.Serializable {


    private int imageId;
    private Product product;
    private String imageUrl;
    private Boolean isMain;
    private LocalDate uploadedDate;
    private LocalDate updatedDate;

    public ProductImage() {
    }


    public ProductImage(int imageId, String imageUrl, LocalDate uploadedDate) {
        this.imageId = imageId;
        this.imageUrl = imageUrl;
        this.uploadedDate = uploadedDate;
    }
    public ProductImage(int imageId, Product product, String imageUrl, Boolean isMain, LocalDate uploadedDate, LocalDate updatedDate) {
        this.imageId = imageId;
        this.product = product;
        this.imageUrl = imageUrl;
        this.isMain = isMain;
        this.uploadedDate = uploadedDate;
        this.updatedDate = updatedDate;
    }

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="image_id", unique=true, nullable=false)
    public int getImageId() {
        return this.imageId;
    }

    public void setImageId(int imageId) {
        this.imageId = imageId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }


    @Column(name="image_url", nullable=false, length=255)
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }


    @Column(name="is_main")
    public Boolean getIsMain() {
        return this.isMain;
    }

    public void setIsMain(Boolean isMain) {
        this.isMain = isMain;
    }


    @Column(name="uploaded_date", nullable=false, length=29)
    public LocalDate getUploadedDate() {
        return this.uploadedDate;
    }

    public void setUploadedDate(LocalDate uploadedDate) {
        this.uploadedDate = uploadedDate;
    }


    @Column(name="updated_date", length=29)
    public LocalDate getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(LocalDate updatedDate) {
        this.updatedDate = updatedDate;
    }


}


