package com.ecommers.model;// default package
// Generated 24-Jun-2025, 10:41:08 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="mobile_number")} 
)
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String email;
     private String mobileNumber;
     private String userRole;
     private Boolean active;
     private Customer customers;

    public Users() {
    }

	
    public Users(Integer userId, String username, String mobileNumber) {
        this.userId = userId;
        this.username = username;
        this.mobileNumber = mobileNumber;
    }
    public Users(Integer userId, String username, String email, String mobileNumber, String userRole, Boolean active,Customer customers) {
       this.userId = userId;
       this.username = username;
       this.email = email;
       this.mobileNumber = mobileNumber;
       this.userRole = userRole;
       this.active = active;
       this.customers = customers;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", unique=true, length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mobile_number", unique=true, nullable=false, length=15)
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    
    @Column(name="user_role", length=200)
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="users")
    public Customer getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customer customers) {
        this.customers = customers;
    }


}


